{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "ZG9ja2VyZHRlc3Q6ZHRlc3RAMTIz"
		}
	}
}
[[runners]]
  environment = ["DOCKER_AUTH_CONFIG={\"auths\":{\"https://index.docker.io/v1\":{\"auth\":\"ZG9ja2VyZHRlc3Q6ZHRlc3RAMTIz=\"}}}"]


k8s-node101 ansible_host=51.222.41.75 ansible_user=gitlabci ansible_password=123@abcd ansible_port=16421 become_user=gitlabci